package com.pluralsight.userregistrationprogram;


import java.io.*;
import java.util.Random;
import java.util.Scanner;
import java.util.regex.Pattern;

public class Main {

    public static void main(String[] args) throws IOException {
        mainMenu();
    }

    public static void mainMenu() throws IOException {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Welcome to my App.");
        System.out.println("From now on you will be part of the PinkSkin community.");
        System.out.println("What would you like to do?");
        System.out.println("1 Make new Account\n2 Login\n3 Delete Account\n4 Exit");
        String option = scanner.next();
        switch (option) {
            case "1" -> newUser();
            case "2" -> loginMenu();
            case "3" -> deleteAccount();
            default -> {
                System.out.println("See you again PigSkin...............");
                System.exit(0);
            }
        }
    }

    public static void newUser() throws IOException {
        System.out.println("Registration App");
        System.out.println("App test ");
        nameRegs();
    }

    public static String nameRegs() throws IOException {

        Scanner scanner = new Scanner(System.in);

        System.out.print("Name: ");
        String name = scanner.nextLine();

        System.out.println("Is this you name: " + name + " " + "Press y to confirm else try again.");
        String confirmation = scanner.nextLine();

        if (!confirmation.equals("y")) {
            nameRegs();
        }
        else surnameRegs(name);
        return name;
    }

    public static String surnameRegs(String name) throws IOException {
        Scanner scanner = new Scanner(System.in);

        System.out.print("Surname: ");
        String surname = scanner.nextLine();

        System.out.println("Is this you name: " + surname + " " + "Press y to confirm else try again.");
        String confirmation = scanner.nextLine();

        if (!confirmation.equals("y")) {
            surnameRegs(name);
        }
        else eMail(name, surname);
        return surname;
    }

    public static String eMail(String name, String surname) throws IOException {
        Scanner scanner = new Scanner(System.in);

        System.out.print("Please enter your email:");
        String email = scanner.nextLine();

        if (!isValid(email)) {
            System.out.println("Invalid Email.");
            eMail(name, surname);
        }
        else if (isValid(email)) {
            boolean hasDuplicate = checkForDuplicates("Email:", email);

            if (hasDuplicate)
                eMail(name, surname);
            else
                userName(name, surname, email);
            return email;
        }
        return email;
    }

    public static String userName(String name, String surname, String email) throws IOException {
        Scanner scanner = new Scanner(System.in);
        Scanner scanner1 = new Scanner(System.in);

        System.out.println("Choose your Username.");
        System.out.println("NOTE: Your user name is unique so it cannot be change");
        System.out.print("Username: ");
        String username = scanner.nextLine();

        if (username.contains(" ")) {
            System.out.println("Username can not contain spaces.");
            userName(name, surname, email);
        }
        else if (!username.contains(" ")) {
            boolean hasDuplicate = checkForDuplicates("User:", username);
            if (hasDuplicate)
                userName(name, surname, email);
            else {
                System.out.println("Is this your Username:" + " " + username + " " + "Press y to confirm else try again.");
                String confirmation = scanner1.nextLine();
                if (confirmation.equals("y")) {
                    passwordOption(name, surname, email, username);

                } else
                    userName(name, surname, email);
            }
        }
        return username;
    }
    public static void passwordOption(String name, String surname, String email, String username) {
        Scanner scanner2 = new Scanner(System.in);

        System.out.print("Password Option:\n1 Autogenerate password \n2 Choose yourself \n3 Exit \n ");
        String passOpt = scanner2.nextLine();
        switch (passOpt) {
            case "1" -> autoGeneratedPass(name, surname, email, username);
            case "2" -> selfChoosePass(name, surname, email, username);
            case "3" -> {
                System.out.println("See you again PigSkin...............");
                System.exit(0);
            }
            default -> {
                System.out.println("Please choose one of the options.");
                passwordOption(name, surname, email, username);
            }
        }

    }

    public static void autoGeneratedPass(String name, String surname, String email, String username) {
        char[] autoGenPass = PasswordGenerator();
        try {
            FileWriter myWriter = new FileWriter("accounts.txt", true);

            BufferedWriter bw = new BufferedWriter(myWriter);
            bw.write(String.format("Name:%30s Surname:%30s Email:%-60s User:%-20s Password:%24s", name, surname, email, username,
                    String.copyValueOf(autoGenPass)));

            System.out.println("Your user name is:" + username);
            System.out.println("Your password is:" + String.valueOf(autoGenPass));
            bw.append("\n");
            bw.close();
            System.out.println("Successfully registered.");
        }
        catch (IOException e) {
            System.out.println("An error occurred.");
            System.out.println("Please try again PickSkin");
            e.printStackTrace();
        }
    }

    public static String selfChoosePass(String name, String surname, String email, String username) {
        Scanner scanner1 = new Scanner(System.in);

        System.out.println("Please introduced a password with at least 8 characters");

        System.out.println("Password: ");
        String pass = scanner1.nextLine();
        System.out.println(pass);

        if (pass.contains(" ")){
            System.out.println("Password can not contain spaces.");
            selfChoosePass(name, surname, email, username);
        }
        else if (pass.isEmpty()){
            System.out.println("Password is empty.");
            selfChoosePass(name, surname, email, username);
        }
        else {
            System.out.print("Confirm Password: ");
            String conf = scanner1.nextLine();
            boolean checkPassword = (pass.equals(conf));

            if (!checkPassword){
                System.out.println("Your password do not match.");
                System.out.println("Try again PinkSkin");
                selfChoosePass(name, surname, email, username);
            }
            else{
                int length1 = pass.length();
                if (length1 < 8) {
                    System.out.println("Password is to short, please introduced a password with at least 8 characters");
                    System.out.println("Try again PinkSkin");
                    selfChoosePass(name, surname, email, username);
                }
                else finalStepRegs(name, surname, email, username, pass);
                return pass;

            }
        }
        return pass;
    }

    public static void finalStepRegs(String name, String surname, String email, String username, String pass){
        try {
            FileWriter myWriter = new FileWriter("accounts.txt", true);
            BufferedWriter bw = new BufferedWriter(myWriter);
            bw.write(String.format("Name:%30s Surname:%30s Email:%-60s User:%-20s Password:%24s", name, surname, email, username, pass));
            bw.append("\n");
            bw.close();
            System.out.println("Your user name is:" + username);
            System.out.println("Your password is:" + pass);
            System.out.println("Successfully registered.");
            System.out.println("Welcome to the community PinkSkin");
        }
        catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }

    public static boolean checkForDuplicates(String type, String value) throws IOException {
        File file = new File("C:\\Users\\valde\\IdeaProjects\\TestProgram\\accounts.txt");
        String[] words = null;
        FileReader fileReader = new FileReader(file);
        BufferedReader bufferedReader = new BufferedReader(fileReader);
        String string;
        String input = type + value;
        while ((string = bufferedReader.readLine()) != null) {
            words = string.split(" ");
            for (String word : words) {
                if (word.equals(input)) {
                    System.out.println("Email already exists.");
                    System.out.println("Please choose another one.");
                    return true;
                }
            }
        }
        return false;
    }

    public static void loginMenu(){

    }

    public static void deleteAccount() {
    }

    private static boolean isValid(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+
                "[a-zA-Z0-9_+&*-]+)*@" +
                "(?:[a-zA-Z0-9-]+\\.)+[a-z" +
                "A-Z]{2,7}$";

        Pattern pat = Pattern.compile(emailRegex);
        if (email == null)
            return false;
        return pat.matcher(email).matches();
    }

    private static char[] PasswordGenerator() {
        String capitalCaseLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String lowerCaseLetters = "abcdefghijklmnopqrstuvwxyz";
        String specialCharacters = "!@#$";
        String numbers = "1234567890";
        String combinedChars = capitalCaseLetters + lowerCaseLetters + specialCharacters + numbers;

        Random random = new Random();
        char[] password = new char[20];

        password[0] = lowerCaseLetters.charAt(random.nextInt(lowerCaseLetters.length()));
        password[1] = capitalCaseLetters.charAt(random.nextInt(capitalCaseLetters.length()));
        password[2] = specialCharacters.charAt(random.nextInt(specialCharacters.length()));
        password[3] = numbers.charAt(random.nextInt(numbers.length()));

        for(int i = 4; i< 20; i++) {
            password[i] = combinedChars.charAt(random.nextInt(combinedChars.length()));
        }
        //System.out.println(password);
        return password;
    }
}