package com.pluralsight.userregistrationprogram;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Random;

public class RandomUserGenerator {



    public static ArrayList<HashMap<String, String>> getRandomUsers(int n) {
        ArrayList<HashMap<String, String>> users = new ArrayList<>();

        /*
        Now use the getRandomUser() method to generate users. Append each user to the users ArrayList
        Finally return the ArrayList of users.
         */
        return users;
    }

    static String passwordGenerator() {
        // Function to autogenerated a new password.
        String capitalCaseLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String lowerCaseLetters = "abcdefghijklmnopqrstuvwxyz";
        String specialCharacters = "!@#$";
        String numbers = "1234567890";
        String combinedChars = capitalCaseLetters + lowerCaseLetters + specialCharacters + numbers;

        Random random = new Random();
        char[] password = new char[20];

        password[0] = lowerCaseLetters.charAt(random.nextInt(lowerCaseLetters.length()));
        password[1] = capitalCaseLetters.charAt(random.nextInt(capitalCaseLetters.length()));
        password[2] = specialCharacters.charAt(random.nextInt(specialCharacters.length()));
        password[3] = numbers.charAt(random.nextInt(numbers.length()));

        for(int i = 4; i< 20; i++) {
            password[i] = combinedChars.charAt(random.nextInt(combinedChars.length()));
        }
        return String.valueOf(password);
    }

    public static void emailAddressesArray() {

        int nameSize = 5;

        String lowerCaseLetters = "abcdefghijklmnopqrstuvwxyz";
        String specialCharacters = "@";
        String specialCharacters1 = ".";

        Random random = new Random();

        int max = lowerCaseLetters.length();
        int rn = random.nextInt() % max;
        char d = lowerCaseLetters.charAt(rn);

        String combinedChars = lowerCaseLetters + specialCharacters + lowerCaseLetters + specialCharacters1 + lowerCaseLetters;

    }
}



